name: RPA de banco # nome do teste

# trigger (gatilho)
on: 
  push:
    branches: ["main"] # e qual a branch que vai gerar o gatilho (["*"] todas as branches)
  pull_request: # o que vai ativar esse gatilho
    branches: ["main"] # e qual a branch que vai gerar o gatilho (["*"] todas as branches)

# define o que ele vai verificar
jobs:
  build:
    runs-on: ubuntu-latest

    # passos a serem executados ex:(roldar o requirements, rodar o python, rodar o banco)
    steps:
      - uses: actions/checkout@v2 # entra na pasta do meu projeto

      - name: Configurar ambiente para o Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.2

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install coverage
          pip install -r requirements.txt

      # - name: Run covarage python
      #   run: |
      #     coverage run app.py

      # - name: Resultados
      #   run: coverage report

      - name: Deploy no EC2 -AWS
        if: github.event_name == 'push'
        run: |
          echo "Conectando no EC2"
          echo "${{ secrets.AWS_CHAVE_PIPELINE_AWS_PEM }}" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ubuntu@"${{ secrets.chave_ubuntu }}" << 'ENDSSH'
            cd /home/ubuntu/RecoopeCompose/IA_Web
            git pull origin main
            cd ..
            bash ./deploy.sh